// File: services/core/esign/server/src/messaging/publisher.contract.test.ts
import { MessageProviderPact } from '@pact-foundation/pact';
import path from 'path';
import { createDocumentSignedEvent } from './factories';

describe('ESign NATS Provider Contract Verification', () => {
  it('verifies generated CloudEvent payloads fulfill consumer Pact contracts', async () => {
    const pact = new MessageProviderPact({
      messageProviders: {
        // Matches the description key generated by the consumer's Pact test suite
        'a compliance document signed CloudEvent': () =>
          Promise.resolve(
            createDocumentSignedEvent(
              'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
              'usr_4412',
              'clr_9910'
            )
          ),
      },
      provider: 'esign-server',
      pactUrls: [
        // Resolves consumer-generated Pact contract files stored in root/workspace pacts directory
        path.resolve(process.cwd(), '../../../../pacts/compliance-server-esign-server.json'),
      ],
    });

    await pact.verify();
  });
});