# File: charts/pdf-service/charts/server/values.yaml

nameOverride: pdf-server

image:
  repository: pdf-server
  tag: prod
  pullPolicy: IfNotPresent

replicas: 1

env: 
  - name: S3_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: minio-credentials
        key: S3_ACCESS_KEY
  - name: S3_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: minio-credentials
        key: S3_SECRET_KEY
  - name: S3_ENDPOINT
    value: "http://minio.platform-local.svc.cluster.local:9000"
  - name: S3_BUCKET
    value: "dsap"
envFrom: []

annotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/metrics"

probes:
  readiness:
    httpGet:
      path: /api/v1/health
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    httpGet:
      path: /api/v1/health
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 10

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
