# File: Dockerfile.base
# syntax=docker/dockerfile:1.7
FROM node:26.7.0-alpine
WORKDIR /app

RUN npm install -g pnpm@11.24.0 --ignore-scripts

COPY tsconfig.json pnpm-workspace.yaml package.json ./
COPY packages/ ./packages
COPY pnpm-lock.yaml ./
RUN --mount=type=cache,id=distributed-platform-pnpm,target=/root/.local/share/pnpm/store \
	pnpm install --frozen-lockfile --ignore-scripts && pnpm build