# File: charts/compliance-shell/values.yaml

ingress:
  web:
    entryPoints:
      - web

  websecure:
    enabled: false
    entryPoints:
      - websecure
    tls: {}

  route:
    rule: "PathPrefix(`/compliance-shell`)"
    serviceName: compliance-shell
