apiVersion: v1
kind: ServiceAccount
metadata:
  name: topology-server
  namespace: platform-local
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: topology-client
  namespace: platform-local
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: topology-db
  namespace: platform-local
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pdf-server
  namespace: platform-local
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pdf-client
  namespace: platform-local
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: compliance-client
  namespace: platform-local
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: topology-shell
  namespace: platform-local
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: compliance-shell
  namespace: platform-local
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: global-shell
  namespace: platform-local
automountServiceAccountToken: false
