# File: services/platform/pdf-generator/compose.dev.yaml
services:
  pdf-server:
    build:
      target: dev
    command: pnpm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./packages:/app/packages
      - ./services/platform/pdf-generator/server:/app/services/platform/pdf-generator/server

  pdf-client:
    build:
      target: dev
    command: pnpm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./packages:/app/packages
      - ./services/platform/pdf-generator/client:/app/services/platform/pdf-generator/client