# File: services/core/topology-service/compose.dev.yaml
services:
  topology-server:
    build:
      target: dev
    image: topology-server:dev
    environment:
      # Forces polling for cross-os volume event reliability
      - CHOKIDAR_USEPOLLING=true
    volumes:
      # Mount source for nodemon/Vite live-reloading
      - ./packages:/app/packages
      - ./services/core/topology-service/server:/app/services/core/topology-service/server
      # Prevent host node_modules from colliding with the container's unprivileged node user
      - /app/services/core/topology-service/server/node_modules

  topology-client:
    build:
      target: dev
    image: topology-client:dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./packages:/app/packages
      - ./services/core/topology-service/client:/app/services/core/topology-service/client
      - /app/services/core/topology-service/client/node_modules