# File: services/core/topology-service/compose.yaml
services:
  topology-db:
    image: neo4j:5.26.0
    container_name: topology-db
    environment:
      - NEO4J_AUTH=${DB_USER}/${DB_PASSWORD}
    ports:
      - "${DB_EXTERNAL_PORT}:7474"
      - "7687:7687"
    volumes:
      - topology_db_data:/data
    networks:
      - platform-mesh
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "cypher-shell -a bolt://localhost:7687 -u \"${DB_USER}\" -p \"${DB_PASSWORD}\" 'RETURN 1' >/dev/null 2>&1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
  topology-server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: topology-server:local
    container_name: topology-server
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
      DB_URI: bolt://topology-db:7687
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      topology-db:
        condition: service_healthy
    volumes:
      - ./server:/app/services/core/topology-service/server
    networks:
      - platform-mesh
  topology-client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: topology-client:local
    container_name: topology-client
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
    volumes:
      - ./client:/app/services/core/topology-service/client
    networks:
      - platform-mesh
    

volumes:
  topology_db_data:

networks:
  platform-mesh:
    name: platform-mesh
