# File: k8s/local/esign-service/client.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esign-client
  namespace: platform-local
spec:
  selector:
    matchLabels:
      app: esign-client
  template:
    metadata:
      labels:
        app: esign-client
    spec:
      serviceAccountName: esign-client
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: esign-client
        image: esign-client:prod
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4012
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
            ephemeral-storage: 128Mi
          limits:
            cpu: 750m
            memory: 512Mi
            ephemeral-storage: 512Mi
        readinessProbe:
          tcpSocket:
            port: 4012
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 4012
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: esign-client
  namespace: platform-local
spec:
  selector:
    app: esign-client
  ports:
  - port: 4012
    targetPort: 4012