# File: k8s/local/esign-service/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: esign-service-ingress
  namespace: platform-local
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - http:
      paths:
      # Route /api/esign to esign-server
      - path: /api/v1/esign
        pathType: Prefix
        backend:
          service:
            name: esign-server
            port:
              number: 4002
      # Route /esign to esign-client frontend
      - path: /esign/client
        pathType: Prefix
        backend:
          service:
            name: esign-client
            port:
              number: 4012