# File: services/platform/esign-service/client/nginx.conf
server {
    listen 3000;
    server_name _;

    location = /health {
        access_log off;
        add_header 'Content-Type' 'text/plain';
        return 200 "healthy\n";
    }

    # Map the E-Sign specific URL prefix
    location /esign/client/ {
        alias /usr/share/nginx/html/;
        index index.html;
        
        # --- REQUIRED FOR MODULE FEDERATION ---
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization' always;

        try_files $uri $uri/ /esign/client/index.html;
    }
}