# File: charts/topology-shell/templates/ingress-websecure.yaml
{{- if .Values.ingress.websecure.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-websecure
  labels:
    app.kubernetes.io/name: topology-shell
    app.kubernetes.io/component: ingress
spec:
  entryPoints:
    {{- toYaml .Values.ingress.websecure.entryPoints | nindent 4 }}
  routes:
    - match: {{ .Values.ingress.route.rule | quote }}
      kind: Rule
      services:
        - name: {{ .Values.ingress.route.serviceName }}
          port: 80
      middlewares:
        - name: gzip-compress
        - name: security-headers
  tls:
    {{- toYaml .Values.ingress.websecure.tls | nindent 4 }}
{{- end }}
